version: 0.2

phases:
    build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on***** `date`
artifacts:
  files:
    - target/myApp.jar